version: 0.2
phases:
  install:
    commands:
      - npm i -g pnpm || npm i -g npm@latest
  build:
    commands:
      - echo Build started on `date`
      - cd dashboard
      - npm ci || npm i
      - npm run build || npm run build --if-present
      - cd ..
artifacts:
  files:
    - '**/*'
  base-directory: 'dashboard/dist'


